name: rtd
channels:
  - defaults
dependencies:
  - python=3.12
  - gettext
  - Jinja2>=3.1.3,<3.2
  - mock
  - pillow
  - pip
  - sphinx>=7.3.7,<7.4
  - sphinx_rtd_theme>=2.0.0,<2.1
  - pip:
    - sphinx-intl>=2.2.0,<2.3
