name: rtd
channels:
  - defaults
dependencies:
  - python=3.9
  - gettext
  - Jinja2<3.1.0
  - mock
  - pillow
  - pip
  - sphinx<4
  - sphinxcontrib_applehelp<1.0.5
  - sphinxcontrib_devhelp<1.0.3
  - sphinxcontrib_htmlhelp<2.0.2
  - sphinxcontrib_qthelp<1.0.4
  - sphinxcontrib_serializinghtml<1.1.6
  - sphinx_rtd_theme<2
  - pip:
    - sphinx-intl
